### ISSUE TITLE
我需要一个点集的delaunay三角剖分，能优先实现吗

### ISSUE THREAD

**Issue by 2020-algorithm** [yszhao91/xtorcga#1]
您好，我需要一个点集delaunay三角剖分，这些点集都是在一个平面上，你能优先实现吗，在此感谢万分!!

**Comment by WREQI** [comment]
您好，我需要一个在模型的某个面上画线或者正方形，然后分割重新生成三角面模型,你能优先实现算法或者提供思路吗，在此感谢万分！

**Comment by yszhao91** [comment]
> 您好，我需要一个点集delaunay三角剖分，这些点集都是在一个平面上，你能优先实现吗，在此感谢万分!!

已经解决
