### ISSUE TITLE
[文档问题] 点到圆圈和点到圆盘的距离缺少Code Example

### ISSUE THREAD

**Issue by CosPie** [yszhao91/xtorcga#5]
缺少了CodeExample 

文档地址：
http://dcgraph.gitee.io/cga.js/guide/distPointAll.html#%E7%82%B9%E5%88%B0%E5%9C%86%E7%9B%98%E7%9A%84%E8%B7%9D%E7%A6%BB

**Comment by yszhao91** [comment]
@CosPie  #6  已经补充
