### ISSUE TITLE
segment.js的set方法bug

### ISSUE THREAD

**Issue by fylinggh** [yszhao91/xtorcga#7]
set(p0: Vec3, p1: Vec3) {

    this[0].copy(p0);

    this[0].copy(p1);

    this.change();

  }
要改为
set(p0: Vec3, p1: Vec3) {

    this[0].copy(p0);

    this[1].copy(p1);

    this.change();
  }

**Comment by yszhao91** [comment]
这个问题已经收到 ，后续版本会纠正

**Comment by yszhao91** [comment]
也可以自己纠正提交，，我会合并，这样你也可以变成贡献者

**Comment by yszhao91** [comment]
已经修正

**Comment by fylinggh** [comment]
我还不太会用github，尽快学会了再来跟你学习




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yszhao91/cga.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月23日(星期四) 上午9:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yszhao91/cga.js] segment.js的set方法bug (Issue #7)





 
也可以最近纠正提交，，我会合并，这样你也可以变成贡献者
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
